### PR TITLE
fix(ui): repair the master compile broken by three parallel merges

### PR DESCRIPTION
**Pull request by simlarsen**
## Why

The **Compile** workflow has been failing on master since 84b6d5e — `compile-dashboard`, `compile-admin-dashboard` and `compile-public-dashboard` are all red.

No individual PR was wrong. Three of them were written against a base that had already moved, and `tsc` only sees the combination.

## What was broken

**1. `Modal` no longer takes `icon`/`iconType`.** `abb09c1c5e` removed those props and swept every caller visible at the time. Three callers on parallel branches weren't in that sweep:

- `ImportSitesFromCsvModal` (`icon`)
- `Pages/Runbook/Agents` (`icon`, `iconType`)
- AdminDashboard `Pages/Health/BackgroundQueues` (`icon`, `iconType`)

```
error TS2322: Property 'icon' does not exist on type 'IntrinsicAttributes & ComponentProps'.
```

**2. `DashboardTableComponent` — `timestampTitle` declared nowhere.** One branch added the `timestampTitle` field to the timestamp rows; another introduced the local `TimestampRow` type and the inline row type on the render callback. The field was written and read but present in neither declaration:

```
error TS2322: Property 'timestampTitle' is missing in type 'TimestampRow'...
error TS2353: Object literal may only specify known properties, and 'timestampTitle' does not exist...
error TS2339: Property 'timestampTitle' does not exist on type '{ timestampIso: string; ... }'.
```

## The fix

Drop the three `icon`/`iconType` prop pairs plus the imports they left unused, and add `timestampTitle: string` to both type declarations. The icons were decorative, so nothing changes for those modals beyond their headers matching every other modal in the product. No behavior changes anywhere — this is the type layer catching up with the merges.

## Verification

- `tsc --noEmit` clean on **Dashboard**, **AdminDashboard** and **PublicDashboard** — the three projects that were failing. Reproduced the exact CI errors locally first, then confirmed they're gone.
- `eslint` clean on all four changed files.

`dep-check` couldn't run locally (it needs a global `npm install -g depcheck`), but it only inspects `package.json` dependencies and no dependency changed.

## Also checked

One **Push Test Images** run also shows failure, but it's a transient Alpine mirror error (`TLS: unspecified error` fetching `APKINDEX.tar.gz`), not a code problem — the next run of that workflow passed. Compile was the only real failure on master.

### CODE REVIEW

**Comment by simlarsen** [comment]
### :white_check_mark: **Snyk checks have passed. No issues have been found so far.**

| Status | Scan Engine |  Critical |  High |  Medium |  Low | Total (0) |
|---|---|---|---|---|---|---|
| :white_check_mark: | Open Source Security| 0 | 0 | 0 | 0 | [ 0 issues](https://app.snyk.io/org/oneuptime-RsC2nshvQ2Vnr35jHvMnMP/pr-checks/31144726-7d1f-4c2e-a7bd-5a596e3cb901?refs=a96ff565e36b60bbe939e32c54840a725fb62a81&source=prChecksComment) |

:computer: Catch issues earlier using the plugins for [VS Code](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner), [JetBrains IDEs](https://plugins.jetbrains.com/plugin/10972-snyk-security), [Visual Studio](https://marketplace.visualstudio.com/items?itemName=snyk-security.snyk-vulnerability-scanner-vs-2022), and [Eclipse](https://marketplace.eclipse.org/content/snyk-security#external-install-button).
